version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: contas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
#  app:
#    image: openjdk:17
#    volumes:
#      - .:/app
#    ports:
      - "8080:8080"
#    depends_on:
#      - db
#    command: ./mvnw spring-boot:run
