version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: contas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_HOSTNAME: http://keycloak:8080
      KEYCLOAK_HOSTNAME_DEBUG: "true"
    command:
      [ "start-dev" ]
    ports:
      - "8080:8080"
    depends_on:
      - db
  app:
    image: desafio-backend-totvs
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    depends_on:
      - keycloak
      - db
    restart: on-failure